elog-gen: handle missing YAML without crashing
The code to build the mako template path was buried inside a
for-loop, which ran against every found YAML file (redundantly).
If, for some reason, the script is configured where the error
YAML is missing, the for-loop never runs and we end up with a
Python crash:

      File "../tools/elog-gen.py", line 167, in gen_elog_hpp
        template = Template(filename=template_path)
    UnboundLocalError: local variable 'template_path' referenced
        before assignment

Pull the template path code out of the for loop to better handle
this case.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ic3dd4e8d9c7a9a9ed4fa382b879ecdc4b1b04838