sdjournal: fix unused parameter error
Seeing the following with higher warning levels:

    ../phosphor-logging/sdjournal.hpp:33:47: error: unused parameter
            ‘fmt’ [-Werror=unused-parameter]
        33 |     virtual int journal_send_call(const char* fmt)

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I5626b8fe7c1f17bc08763f69ae040891d22cf1e9