build: add callouts-gen dependencies
`elog_meta.cpp` requires `callouts-gen.hpp` which is created by the
`callouts-gen` target.  Whenever we reference `elog_meta.cpp` as a
source file we also need to have `callouts-gen` listed as a source,
otherwise there are unsatisfied headers and we end up with the
following ninja race condition:

```
| [4/47] arm-openbmc-linux-gnueabi-g++ ... -o phosphor-rsyslog-config/phosphor-rsyslog-conf.p/.._elog_meta.cpp.o -c ../git/elog_meta.cpp
...
| In file included from ../git/elog_meta.cpp:3:
| ../git/elog_meta.hpp:5:10: fatal error: callouts-gen.hpp: No such file or directory
|     5 | #include "callouts-gen.hpp"
|       |          ^~~~~~~~~~~~~~~~~~
| compilation terminated.
...
| [6/47] .../python3 ... -o callouts-gen.hpp
```

Add these dependencies as appropriate to avoid build races.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I3ed027bf1e25232f367de828a8b18c55249f960c