PEL:test: Workaround new compiler issue
For reasons I'm not sure of, the compiler is now failing on a
vector.resize() complaining about an array out of bounds with the
errors shown below.

Change the testcase to just initially create the vector to be 71 bytes
instead of 72 and then resizing to 71.

This appears to only fail with a gcc 15.2 installed locally for
standalone builds, and not with the one in CI.

```
[120/184] Compiling C++ object test/openpower-pels/test-openpower-pels-src.p/src_test.cpp.o
FAILED: test/openpower-pels/test-openpower-pels-src.p/src_test.cpp.o
...
    inlined from ‘virtual void SRCTest_TestGetProgressCode_Test::TestBody()’ at ../test/openpower-pels/src_test.cpp:1609:19:

/usr/include/c++/15/bits/stl_construct.h:133:7: error: array subscript 72 is outside array bounds of ‘unsigned char [72]’ [-Werror=array-bounds=]
  133 |       ::new(static_cast<void*>(__p)) _Tp(std::forward<_Args>(__args)...);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/c++/15/bits/c++allocator.h:33,
                 from /usr/include/c++/15/bits/allocator.h:46,
                 from /usr/include/c++/15/bits/alloc_traits.h:39,
                 from /usr/include/c++/15/ext/alloc_traits.h:36,
                 from /usr/include/c++/15/bits/hashtable_policy.h:39,
                 from /usr/include/c++/15/bits/hashtable.h:37,
                 from /usr/include/c++/15/bits/unordered_map.h:33,
                 from /usr/include/c++/15/unordered_map:43,
                 from /usr/include/c++/15/functional:65,
                 from ../subprojects/nlohmann_json/single_include/nlohmann/json.hpp:23:
In member function ‘_Tp* std::__new_allocator<_Tp>::allocate(size_type, const void*) [with _Tp = unsigned char]’,
    inlined from ‘constexpr _Tp* std::allocator< <template-parameter-1-1> >::allocate(std::size_t) [with _Tp = unsigned char]’ at /usr/include/c++/15/bits/allocator.h:203:40,
    inlined from ‘static constexpr _Tp* std::allocator_traits<std::allocator<_Up> >::allocate(allocator_type&, size_type) [with _Tp = unsigned char]’ at /usr/include/c++/15/bits/alloc_traits.h:614:28,
    inlined from ‘constexpr std::_Vector_base<_Tp, _Alloc>::pointer std::_Vector_base<_Tp, _Alloc>::_M_allocate(std::size_t) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /usr/include/c++/15/bits/stl_vector.h:387:33,
    inlined from ‘constexpr void std::vector<_Tp, _Alloc>::_M_range_initialize_n(_Iterator, _Sentinel, size_type) [with _Iterator = const unsigned char*; _Sentinel = const unsigned char*; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /usr/include/c++/15/bits/stl_vector.h:1985:23,
    inlined from ‘constexpr std::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /usr/include/c++/15/bits/stl_vector.h:712:23,
    inlined from ‘virtual void SRCTest_TestGetProgressCode_Test::TestBody()’ at ../test/openpower-pels/src_test.cpp:1608:62:
/usr/include/c++/15/bits/new_allocator.h:151:73: note: at offset 72 into object of size 72 allocated by ‘operator new’
  151 |         return static_cast<_Tp*>(_GLIBCXX_OPERATOR_NEW(__n * sizeof(_Tp)));
      |                                                                         ^
```

Change-Id: I5f6e4b2b1137138ad7954ce6ab709cf318b05a5b
Signed-off-by: Matt Spinler <spinler@us.ibm.com>