test:openpower-pels fix unused result warning
Replace std::ranges::any_of() with an explicit loop to avoid
ignoring its nodiscard return value.

Error details:
'''
    ../test/openpower-pels/pel_test.cpp:1317:24: error: ignoring return value of
    ‘constexpr bool std::ranges::__any_of_fn::operator()(_Range&&, _Pred, _Proj)
    const [with _Range = const std::vector<std::unique_ptr<openpower::pels::Section> >&; _Proj = std::identity;
     _Pred = getDIMMInfo<openpower::pels::PEL>(const openpower::pels::PEL&)::<lambda(const auto:76&)>]’,
     declared with attribute ‘nodiscard’ [-Werror=unused-result]
'''

Change-Id: I8305035ea9704ec43f5be6ffea6a5f54714c2bad
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>