PEL:clang-tidy: Removed unused constants
Fix clang-tidy errors like:
```
../extensions/openpower-pels/tools/peltool.cpp:39:16: error: unused variable 'logging' [clang-diagnostic-unused-const-variable]
   39 | constexpr auto logging = "xyz.openbmc_project.Logging";
      |                ^~~~~~~
```

Change-Id: I7b0db7fe0150937b1a5eb389ea68ef82574f3998
Signed-off-by: Matt Spinler <spinler@us.ibm.com>