PEL: fix bitbake failures related to commit e0538848
failure 1:
   ../git/extensions/openpower-pels/meson.build:47:4:
   ERROR: Tried to use 'add_project_arguments' after a
   build target has been declared. This is not permitted.
   Please declare all arguments before your targets.
   Fix : Removed add_project_arguments is not required
         for SBE_FFDC_SUPPORTED feature. cpp compiler
         option is set by default and "c" type build is
         not used.
failure 2:
   fatal error: phosphor-logging/log.hpp: No such file
   or directory
   Fix : Added header file include path in meson build.

Tested: Unit testing is successfull

Signed-off-by: Jayanth Othayoth <ojayanth@in.ibm.com>
Change-Id: I880ad5d0c80f6b4ded69c6575657398008d28b91