openpower-pels: fapi_data_process: fix for fmt-9
The latest fmt v9 fails with a compile error in fapi_data_process:

```
...
include/fmt/core.h:2743:12: error: use of deleted function 'fmt::v9::detail::fallback_formatter<T, Char, Enable>::fallback_formatter() [with T = unsigned char [21]; Char = char; Enable = void]'
...
../git/extensions/openpower-pels/fapi_data_process.cpp:168:36:   required from here
```

Switched the code to use a fmt::join call to process the byte array
into a hex output.

Tested:

Manually modified a testcase as follows and observed reasonable output:
```
    typedef uint8_t ATTR_PHYS_BIN_PATH_Type[21];
    ATTR_PHYS_BIN_PATH_Type bar{0x01, 0x02, 0x03, 0x04, 0x42, 0x00};
    std::cout << fmt::format("Given ATTR_PHYS_BIN_PATH value({:02x}) "
                        "not found in phal device tree",
                        fmt::join(bar, "")).c_str() << std::endl;
```

```
Given ATTR_PHYS_BIN_PATH value(010203044200000000000000000000000000000000) not found in phal device tree
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I525a6dc48ea780c05f7207753b7663db536a5897