PEL: fix bitbake failures related to commit e0538848
fatal error: phosphor-logging/log.hpp: No such file
or directory.

Fix: Added phosphor_logging_dep to pel dependencies.

Tested: Unit testing is successfull.
        Created and verified SBE failure related PEL.

Signed-off-by: Jayanth Othayoth <ojayanth@in.ibm.com>
Change-Id: I880ad5d0c80f6b4ded69c6575657398008d28b91