PEL:test: Fix deprecated warnings with new gmock
The new version of gmock was complaining that the use of Invoke() for a
callable was deprecated, so remove it.

```
../subprojects/googletest/googlemock/include/gmock/gmock-actions.h:2059:41: note: declared here
 2059 | typename std::decay<FunctionImpl>::type Invoke(FunctionImpl&& function_impl) {
      |                                         ^~~~~~
../test/openpower-pels/host_notifier_test.cpp:489:31: error: ‘typename std::decay<_Tp>::type testing::Invoke(FunctionImpl&&) [with FunctionImpl = HostNotifierTest_TestCannotStartCmd_Test::TestBody()::<lambda(uint32_t, uint32_t)>&; typename std::decay<_Tp>::type = HostNotifierTest_TestCannotStartCmd_Test::TestBody()::<lambda(uint32_t, uint32_t)>]’ is deprecated: Actions can now be implicitly constructed from callables. No need to create wrapper objects using Invoke(). [-Werror=deprecated-declarations]
  489 |         .WillRepeatedly(Invoke(sendSuccess));
```

Change-Id: Id698baa8eefbe7e2b632bf8e5e750df69e088312
Signed-off-by: Matt Spinler <spinler@us.ibm.com>