elog: ensure new sdbusplus events cannot be committed directly
sdbusplus events should not be committed in the old way, because
they have their metadata directly in the class rather than using
the side-band metadata YAML (from phosphor-logging).  Add compile-time
asserts to ensure they cannot be used with the older interfaces.

Tested:

Create a simple test:
```
    phosphor::logging::report<
        sdbusplus::event::xyz::openbmc_project::Logging::Cleared>();
```

Which fails to compile as follows:
```
In file included from ../test/basic_event_commit.cpp:3:
../lib/include/phosphor-logging/elog.hpp: In instantiation of ‘uint32_t phosphor::logging::report(Args ...) [with T = sdbusplus::event::xyz::openbmc_project::Logging::Cleared; Args = {}; uint32_t = unsigned int]’:
../test/basic_event_commit.cpp:13:66:   required from here
../lib/include/phosphor-logging/elog.hpp:205:15: error: static assertion failed: T must NOT be an sdbusplus::generated_event
  205 |         !std::is_base_of_v<sdbusplus::exception::generated_event<T>, T>,
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I9cfc6915d125545067082a4fff717443aedd1531