exception: switch to public sdbus exception
SdBusError was intended to be a private error type inside sdbusplus.
Switch all catch locations to use the general sdbusplus::exception type.

For now, it is still OK for the testcases to throw them.

Signed-off-by: Matt Spinler <spinler@us.ibm.com>
Change-Id: I054220d05e4a54d1a3c6b3df2a02d7d48ede9fde