clang-tidy: guard optional accesses in tests
Introduce explicit control flow before dereferencing std::optional in
remote logging tests to satisfy bugprone-unchecked-optional-access.
This ensures clang-tidy compliance and prevents false positives while
keeping test logic clear and robust. No functional changes.

Fixed below errors
'''
../test/remote_logging_test_config.cpp:80:28: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
   80 |     EXPECT_EQ(std::get<0>(*ret), "abcd:ef01::01");
      |                            ^
../test/remote_logging_test_config.cpp:81:28: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
   81 |     EXPECT_EQ(std::get<1>(*ret), 50000);
      |                            ^
../test/remote_logging_test_config.cpp:145:28: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
  145 |     EXPECT_EQ(std::get<2>(*ret),
      |                            ^
../test/remote_logging_test_config.cpp:156:28: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
  156 |     EXPECT_EQ(std::get<2>(*ret),
      |                            ^
'''

Change-Id: I848fd54dbdc2e2d133c78ee9c729f29173e0bbe1
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>